### ISSUE TITLE
error WARNING Found '$ha_price_default' 

### ISSUE THREAD

**Issue by JakobM999** [zenzay/esphome-power-meter#3]
INFO ESPHome 2023.8.2
INFO Reading configuration /config/esphome/sprsun_power_meter.yaml...
WARNING Found '$ha_price_default' (see number->4->initial_value) which looks like a substitution, but 'ha_price_default' was not declared
WARNING Found '$ha_price_default' (see number->4->initial_value) which looks like a substitution, but 'ha_price_default' was not declared
WARNING GPIO12 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Detected timezone 'Europe/Copenhagen'
Failed config

number.template: [source /config/esphome/sprsun_power_meter.yaml:182]
  platform: template
  name: Set kWh Price
  icon: mdi:cash-100
  unit_of_measurement: DKK/kWh
  optimistic: True
  mode: box
  min_value: 0
  max_value: 100
  step: 0.001
  
  expected float.
  initial_value: $ha_price_default
  disabled_by_default: True
  entity_category: config
  on_value: 
    lambda: id(price_per_kwh) = x;
    id(update_price_kwh_avg).execute();
    
Do You know why i get this error WARNING Found '$ha_price_default' (see number->4->initial_value) which looks like a substitution, but 'ha_price_default' was not declared
Am i missing some settings i HA, i  use "ha_price_sensor: 'energi_data_service'" and not nordpol as You do, don't know if that is the problem.
Power Meter v0.9.2 works just fine.

**Comment by JakobM999** [comment]
if i do a fix price then i works :  initial_value: 0.323 #$ha_price_default

Where is $ha_price_default set?

- platform: template
    name: 'Set kWh Price'
    icon: mdi:cash-100
    unit_of_measurement: '${currency}/kWh'
    optimistic: true
    mode: box
    min_value: 0
    max_value: 100
    step: 0.001
    initial_value: 0.323 #$ha_price_default
    disabled_by_default: true
    entity_category: 'config'
    on_value:
      lambda: |-
        id(price_per_kwh) = x;
        id(update_price_kwh_avg).execute();

**Comment by zenzay** [comment]
Hi, yeah sorry. I removed it earlier as I thought I wasn't using the substitution anymore. I have put it back now.

```
 ha_price_default: '2'
```
